/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthAgendaRouteImport } from './routes/_auth.agenda'
import { Route as AuthAjudaRouteImport } from './routes/_auth.ajuda'
import { Route as AuthAssistenteRouteImport } from './routes/_auth.assistente'
import { Route as AuthConfiguracoesRouteImport } from './routes/_auth.configuracoes'
import { Route as AuthCrmRouteImport } from './routes/_auth.crm'
import { Route as AuthEquipeRouteImport } from './routes/_auth.equipe'
import { Route as AuthEstoqueRouteImport } from './routes/_auth.estoque'
import { Route as AuthFinanceiroRouteImport } from './routes/_auth.financeiro'
import { Route as AuthMarketingRouteImport } from './routes/_auth.marketing'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthRelatoriosRouteImport } from './routes/_auth.relatorios'
import { Route as AgendarOrgSlugRouteImport } from './routes/agendar.$orgSlug'
import { Route as AuthAtendimentosIndexRouteImport } from './routes/_auth.atendimentos.index'
import { Route as AuthAtendimentosIdRouteImport } from './routes/_auth.atendimentos.$id'
import { Route as AuthClientesIndexRouteImport } from './routes/_auth.clientes.index'
import { Route as AuthClientesIdRouteImport } from './routes/_auth.clientes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgendaRoute = AuthAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAjudaRoute = AuthAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssistenteRoute = AuthAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfiguracoesRoute = AuthConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCrmRoute = AuthCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEquipeRoute = AuthEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEstoqueRoute = AuthEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinanceiroRoute = AuthFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMarketingRoute = AuthMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosRoute = AuthRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthRoute,
} as any)
const AgendarOrgSlugRoute = AgendarOrgSlugRouteImport.update({
  id: '/agendar/$orgSlug',
  path: '/agendar/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAtendimentosIndexRoute = AuthAtendimentosIndexRouteImport.update({
  id: '/atendimentos/',
  path: '/atendimentos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAtendimentosIdRoute = AuthAtendimentosIdRouteImport.update({
  id: '/atendimentos/$id',
  path: '/atendimentos/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesIndexRoute = AuthClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientesIdRoute = AuthClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agenda': typeof AuthAgendaRoute
  '/ajuda': typeof AuthAjudaRoute
  '/assistente': typeof AuthAssistenteRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/crm': typeof AuthCrmRoute
  '/equipe': typeof AuthEquipeRoute
  '/estoque': typeof AuthEstoqueRoute
  '/financeiro': typeof AuthFinanceiroRoute
  '/marketing': typeof AuthMarketingRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/agendar/$orgSlug': typeof AgendarOrgSlugRoute
  '/atendimentos/$id': typeof AuthAtendimentosIdRoute
  '/clientes/$id': typeof AuthClientesIdRoute
  '/atendimentos/': typeof AuthAtendimentosIndexRoute
  '/clientes/': typeof AuthClientesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agenda': typeof AuthAgendaRoute
  '/ajuda': typeof AuthAjudaRoute
  '/assistente': typeof AuthAssistenteRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/crm': typeof AuthCrmRoute
  '/equipe': typeof AuthEquipeRoute
  '/estoque': typeof AuthEstoqueRoute
  '/financeiro': typeof AuthFinanceiroRoute
  '/marketing': typeof AuthMarketingRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/agendar/$orgSlug': typeof AgendarOrgSlugRoute
  '/': typeof AuthIndexRoute
  '/atendimentos/$id': typeof AuthAtendimentosIdRoute
  '/clientes/$id': typeof AuthClientesIdRoute
  '/atendimentos': typeof AuthAtendimentosIndexRoute
  '/clientes': typeof AuthClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/agenda': typeof AuthAgendaRoute
  '/_auth/ajuda': typeof AuthAjudaRoute
  '/_auth/assistente': typeof AuthAssistenteRoute
  '/_auth/configuracoes': typeof AuthConfiguracoesRoute
  '/_auth/crm': typeof AuthCrmRoute
  '/_auth/equipe': typeof AuthEquipeRoute
  '/_auth/estoque': typeof AuthEstoqueRoute
  '/_auth/financeiro': typeof AuthFinanceiroRoute
  '/_auth/marketing': typeof AuthMarketingRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/relatorios': typeof AuthRelatoriosRoute
  '/agendar/$orgSlug': typeof AgendarOrgSlugRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/atendimentos/$id': typeof AuthAtendimentosIdRoute
  '/_auth/clientes/$id': typeof AuthClientesIdRoute
  '/_auth/atendimentos/': typeof AuthAtendimentosIndexRoute
  '/_auth/clientes/': typeof AuthClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/agenda'
    | '/ajuda'
    | '/assistente'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/marketing'
    | '/onboarding'
    | '/relatorios'
    | '/agendar/$orgSlug'
    | '/atendimentos/$id'
    | '/clientes/$id'
    | '/atendimentos/'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/agenda'
    | '/ajuda'
    | '/assistente'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/marketing'
    | '/onboarding'
    | '/relatorios'
    | '/agendar/$orgSlug'
    | '/'
    | '/atendimentos/$id'
    | '/clientes/$id'
    | '/atendimentos'
    | '/clientes'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/agenda'
    | '/_auth/ajuda'
    | '/_auth/assistente'
    | '/_auth/configuracoes'
    | '/_auth/crm'
    | '/_auth/equipe'
    | '/_auth/estoque'
    | '/_auth/financeiro'
    | '/_auth/marketing'
    | '/_auth/onboarding'
    | '/_auth/relatorios'
    | '/agendar/$orgSlug'
    | '/_auth/'
    | '/_auth/atendimentos/$id'
    | '/_auth/clientes/$id'
    | '/_auth/atendimentos/'
    | '/_auth/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AgendarOrgSlugRoute: typeof AgendarOrgSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agenda': {
      id: '/_auth/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthAgendaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ajuda': {
      id: '/_auth/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthAjudaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assistente': {
      id: '/_auth/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthAssistenteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuracoes': {
      id: '/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthConfiguracoesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/crm': {
      id: '/_auth/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthCrmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/equipe': {
      id: '/_auth/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthEquipeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/estoque': {
      id: '/_auth/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthEstoqueRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/financeiro': {
      id: '/_auth/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthFinanceiroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/marketing': {
      id: '/_auth/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthMarketingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios': {
      id: '/_auth/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthRelatoriosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/agendar/$orgSlug': {
      id: '/agendar/$orgSlug'
      path: '/agendar/$orgSlug'
      fullPath: '/agendar/$orgSlug'
      preLoaderRoute: typeof AgendarOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/atendimentos/': {
      id: '/_auth/atendimentos/'
      path: '/atendimentos'
      fullPath: '/atendimentos/'
      preLoaderRoute: typeof AuthAtendimentosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/atendimentos/$id': {
      id: '/_auth/atendimentos/$id'
      path: '/atendimentos/$id'
      fullPath: '/atendimentos/$id'
      preLoaderRoute: typeof AuthAtendimentosIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes/': {
      id: '/_auth/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthClientesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clientes/$id': {
      id: '/_auth/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthClientesIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAgendaRoute: typeof AuthAgendaRoute
  AuthAjudaRoute: typeof AuthAjudaRoute
  AuthAssistenteRoute: typeof AuthAssistenteRoute
  AuthConfiguracoesRoute: typeof AuthConfiguracoesRoute
  AuthCrmRoute: typeof AuthCrmRoute
  AuthEquipeRoute: typeof AuthEquipeRoute
  AuthEstoqueRoute: typeof AuthEstoqueRoute
  AuthFinanceiroRoute: typeof AuthFinanceiroRoute
  AuthMarketingRoute: typeof AuthMarketingRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRelatoriosRoute: typeof AuthRelatoriosRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAtendimentosIdRoute: typeof AuthAtendimentosIdRoute
  AuthClientesIdRoute: typeof AuthClientesIdRoute
  AuthAtendimentosIndexRoute: typeof AuthAtendimentosIndexRoute
  AuthClientesIndexRoute: typeof AuthClientesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgendaRoute: AuthAgendaRoute,
  AuthAjudaRoute: AuthAjudaRoute,
  AuthAssistenteRoute: AuthAssistenteRoute,
  AuthConfiguracoesRoute: AuthConfiguracoesRoute,
  AuthCrmRoute: AuthCrmRoute,
  AuthEquipeRoute: AuthEquipeRoute,
  AuthEstoqueRoute: AuthEstoqueRoute,
  AuthFinanceiroRoute: AuthFinanceiroRoute,
  AuthMarketingRoute: AuthMarketingRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRelatoriosRoute: AuthRelatoriosRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAtendimentosIdRoute: AuthAtendimentosIdRoute,
  AuthClientesIdRoute: AuthClientesIdRoute,
  AuthAtendimentosIndexRoute: AuthAtendimentosIndexRoute,
  AuthClientesIndexRoute: AuthClientesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AgendarOrgSlugRoute: AgendarOrgSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
